### ISSUE TITLE
Question, Question Question

### ISSUE THREAD

**Issue by gussandy** [copleykj/Mesosphere#58]
hi,
1. Can I use other form validation events such as keyup, blur etc with Mesosphere? I've taking a quick pick at the source code and it seems form validation only occurs on form submission.
2. I would like to display all error messages form-wide like the image below
![screen shot 2015-01-30 at 14 35 55](https://cloud.githubusercontent.com/assets/5196153/5977280/3d79692c-a88e-11e4-83b5-799d833d0c42.png)
and not directly underneath each key. Is this possible with Mesosphere?
3. My validation error messages are dependent on the kind of input been entered, therefore how do I handle conditional error messages with Mesosphere?
4. Additionally, I would like to create custom validation functions such as no duplicate value etc. iterating through other fields within the array to determine validation state. How do I handle this with Mesosphere?

Your thoughts on these questions would be greatly appreciated.

Thnaks

**Comment by copleykj** [comment]
>Can I use other form validation events such as keyup, blur etc with Mesosphere? I've taking a quick pick at the source code and it seems form validation only occurs on form submission.

You can set these up manually as events on the form or input, but Mesosphere doesn't provide this functionality.

> I would like to display all error messages form-wide like the image below and not directly underneath each key. Is this possible with Mesosphere?

Sure, by default the errors are just inserted into elements with the id of fieldName-error like <span id="password-error"> you can place these anywhere you want and due to the nature of html any that don't contain any text will collapse completely. You can also override the default functionality by using the onFailure option.

>My validation error messages are dependent on the kind of input been entered, therefore how do I handle conditional error messages with Mesosphere?

Mesosphere doesn't have the ability to have error messages that change depending on conditions.. You might be able to make something work by overriding the default onFailure handler

>Additionally, I would like to create custom validation functions such as no duplicate value etc. iterating through other fields within the array to determine validation state. How do I handle this with Mesosphere?

This should be able to be accomplished by extending Mesosphere with your own rules, formats, transforms, or aggregates. See https://github.com/copleykj/Mesosphere#extending

**Comment by gussandy** [comment]
@copleykj thanks a million for your response. great help. cheers
